name: Run webhook_push.py

on:
  push:
    branches:
      - main

jobs:
  run-webhook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run webhook_push.py
      run: python webhook_push.py
